apiVersion: v1
kind: ConfigMap
metadata:
  name: be-pro-config
data:
  PORT: "5004"
  CLIENT: 20.197.104.123
  MONGO_URI: mongodb://db-service-pro:27017/db-pro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finosys-be-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-pro
  template:
    metadata:
      labels:
        app: be-pro
    spec:
      containers:
      - image: fazzyaziz/finosys-be-pro:latest
        name: container-be-pro
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5004
        envFrom:
        - configMapRef:
            name: be-pro-config
---
apiVersion: v1
kind: Service
metadata:
  name: be-pro-service
spec:
  ports:
  - port: 5004
    targetPort: 5004
  selector:
    app: be-pro
  type: LoadBalancer