apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pro
spec:
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 1Gi
 hostPath:
   path: /tmp/pv-pro
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pro
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""

