apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-user
spec:
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 1Gi
 hostPath:
   path: /tmp/pv-user
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-user
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: db-user
  labels:
    app: db-user
spec:
  volumes:
  - name: pv-user
    persistentVolumeClaim:
      claimName: pvc-user
  containers:
  - image: mongo
    name: container-user
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: pv-user
      mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-user
  name: db-user
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: db-user
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finosys-user-config
data:
  PORT: "5000"
  CLIENT: 20.197.104.123
  MONGO_URI: mongodb://db-user:27017/db-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finosys-user-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finosys-user
  template:
    metadata:
      labels:
        app: finosys-user
    spec:
      containers:
      - image: fazzyaziz/finosys-users:latest
        name: container-user
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: finosys-user-config
        - secretRef:
            name: jwtsec

---
apiVersion: v1
kind: Service
metadata:
  name: finosys-user-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: finosys-user
  type: LoadBalancer
